FROM kestr3l/stable-diffusion-webui:1.2.2 as build

WORKDIR /home/user/
RUN mkdir kohya_ss
WORKDIR /home/user/kohya_ss
COPY . .
RUN ls -la
RUN chmod +x /home/user/kohya_ss/setup.sh
RUN make
#ENTRYPOINT ["/home/user/kohya_ss/setup.sh"]